* ***Policy:** Cyber security policies are rules and guidelines that outline an organisation's approach to cyber security. By establishing and implementing clear policies and procedures, organisations can ensure that their security measures are consistently applied across the organisation. Configuring an appropriate execution policy was another control that proved effective in inhibiting attack pathways, being utilised in 20 out of the 45 incidents.
* ***Encryption:** Encryption involves encoding data so that it can only be read by authorised parties. The implementation of encryption can help the organisation to secure sensitive data and prevent unauthorised access. Encryption was used in 9 out of 45 incidents, highlighting the effectiveness of strong encryption measures to prevent unauthorised access to sensitive data.
* ***Backup:** Backup refers to making regular replicas of data and storing them in a secure location. This is a crucial security measure in the case of ransomware, or other incidents where data may be damaged or deleted. By establishing a backup(s), organisations can ensure that data is accessible even in the case of disaster. We reconstructed 9 cases of ransomware, where backup, as a control, can support organisations to recover from such cyber attacks and minimise the impact of data loss.

Overall, these findings suggest that implementing AC with CE can be a practical approach to reducing the attack surface and consequently the blast radius.

RQ3: Identify specific inhibition patterns (CE or AC) with regards to ransomware incidents in the corpus.

We investigated 9 cases of ransomware attacks, where the variants included Black Basta, Conti, Lockbit among others. Our analysis was conducted in two phases. The first phase involved determining the overall controls employed, including both CE and AC, as well as the combination of both, to prevent the attacks going further in a tree. In the second phase, we performed detailed analysis and examined the controls at L1, P1 and L1PI1 to determine which controls were effective in halting the progression of events in the IFT. Our findings are presented in Figure 10. The blue, red and yellow bar represents the CE controls, AC and combination of both controls respectively.

Figure 10 (a) displays the distribution of controls utilised in the different ransomware incidents. In cases 1 and 9 it is observed that CE controls alone mitigate the majority of attack pathways. The phenomenon is the same for cases 4, 5, 6, 7 & 8 where CE controls by themselves are appropriate to mitigate most attack pathways, however AC and combination of AC & CE controls are applicable to mitigate the remaining attack pathways. On the other hand, for case 2, CE & AC controls are independently applicable to mitigate an equal number of attack pathways. Case 3 is an exception, where our findings show that a combination of CE & AC are suitable to mitigate more attack pathways than they do when applied independently.

Figure 10 (b) presents the effectiveness of controls from preventing an attack if proceed beyond L1; we find that CE controls can be applied to stop a ransomware attack in cases 4 & 9. In our investigations we find the applicability of a combination of CE & AC in case 6 only to prevent an attack at L1. However, for all the other instances of ransomware attack we find that application of AC to be effective at L1.

The phase analysis as presented in Figure 10 (c) shows that CE by themselves are appropriate to prevent more attack pathways at the initial phase but they need to be supported with a combination of CE & AC controls. For cases 1, 3, 4, 8 7, CE controls and a combination of CE & AC are evenly poised in their ability to prevent attack pathways at the initial phase.