## 8 Discussion

### Need for Additional Controls

CE were designed as a set of usable & affordable controls intended to be used by organisations. They focus on patch management, access control, malware protection, firewall and secure configuration. The proposed controls point to basic hygiene that an organisation should practice to prevent security breaches. The assumption is that attackers are opportunistic, and all attackers do not come with formidable expertise.

We studied the attack scenarios by phases, levels, and a combination of the two, along with an overall analysis of the entire attack lifecycle. While CE controls seem to be effective in preventing many malicious attack pathways from propagating beyond the initial phases & levels, there remains a need for AC to mitigate the attacks when they progress further into the systems and networks. Furthermore, the need for AC cannot be completely ruled out even at the initial stages. We identify some AC - encryption, backup, policy, education, logging & monitoring. Consequently, we see two distinct lines of deliberations here. One is on the need for AC; the other being, should there be a need for AC, then deliberating on the underpinning knowledge for a CE assessor.

Considering AC includes a fundamental debate as to whether controls should only be preventive and not include mechanisms that help in recovery. On the other hand, our results show that while attacks propagate beyond the initial levels and phases there is indeed a need for AC. The argument for AC can be grounded upon the idea that it is difficult to anticipate all possible attack pathways and harden systems such that attacks can be prevented from progressing beyond the initial stages. With respect to the need for recovery mechanisms, there are applications where recovery is integral to intrusion and fault tolerance [4] and an important ingredient of cyber resilience [19]. Protection mechanisms need to evolve across space and time [6].

Should there be AC as part of CE, the other pertinent question is redesigning the syllabus for a CE assessor. Prior research conducted a systematic mapping with CyBOK and found that _cloud security_ and _applied cryptography_ covers the skills that an assessor needs. Based on our analysis, a further expansion of the syllabus could include the _human factors_ and _security operations and incident management_ Knowledge Areas (these are already partly covered in the syllabus, albeit not extensively). Future research could consider mapping the ingredients of the AC to elicit relevant Knowledge Areas.

**Take Away.** CE controls are effective in preventing attacks at their inception, but need the support of Additional Controls if attacks penetrate further into an organisation's systems & networks. Deliberations on AC spawn a foundational debate as to whether controls should only be pre-emptive and exclude recovery from breaches. Should there be recognition of AC as essential then CE assessors need to be skilled in _human factors_ and _security operations and incident management_.

### Deployment of the controls

The _inhibit gates_ indicate controls that can protect against breaches expanding within an organisation. Our investigations reveal that the deployment of controls needs to be contextualised. To that we propose two possibilities for effective deployment of controls.

Sequential ControlsInhibit gates refer to the controls that must be activated in a specific order to mitigate the particular event effectively. These controls should be implemented in a specific sequence, where each inhibit gate depends on the previous one to work successfully. For example, in a phishing attack which is trying to perform privilege escalation, the inhibit gates involve User Education (m1), Multi-factor Authentication (m2) and Monitoring the logging attempts (m3). These three controls should be in the sequence (m1-m2-m3) as shown in Figure 11 and executed correctly; otherwise, overall cyber controls could fail.

Parallel controlsParallel inhibit gates work independently and ensure that if one control fails, other controls are in place and sufficient to prevent the attack (Figure 12). For example, in the case of unauthorised access to an account, the most common used security controls, such as user access control (m1), multi-factor Authentication (m2) and firewall