baseURL = "https://devfest.modena.it/"
title = "DevFest Modena 2026"

# Language
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = false

# Output
disableKinds = ["taxonomy"]
disableHugoGeneratorInject = true
enableGitInfo = true
enableRobotsTXT = true

# Markup
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
[markup.goldmark]
[markup.goldmark.renderHooks]
[markup.goldmark.renderHooks.link]
enableDefault = true

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate", ":fileModTime"]

# Custom params

[params]
author = "GDG Cloud Modena"
company = "GDG Cloud Modena"
email = "info@devfest.modena.it"
subject = "evento, event, tech, stem, devfest"
copyrightFromYear = 2024
favicon = true
hidden = false
simpleAnalyticsDomain = "sa.devfest.modena.it"
utm = "utm_source=website&utm_medium=referral&utm_campaign=devfest_modena_2026"
ticketsUrl = "https://gdg.community.dev/e/m6u46s/"
currentEdition = 2026
cvFormUrl = "https://form.asana.com/?k=qpheZ_rD3DLkDmIjsJaKVA&d=588515525965352"
callForSpeakersEnabled = false
sessionizeUrl = "https://sessionize.com/devfest-modena-2026"

[params.social]
LinkedIn = "https://www.linkedin.com/showcase/devfest-modena/"
Instagram = "https://www.instagram.com/devfest.modena/"
Facebook = "https://www.facebook.com/events/1308374207349867"
Telegram = "https://t.me/devfest_modena"

# Languages and Menus

[languages]
  [languages.it]
    languageCode = "it-IT"
    languageName = "Italiano"
    languageDirection = "ltr"
    title = "DevFest Modena 2026"
    weight = 1
    [languages.it.params]
      brand = "DevFest Modena"
      tagline = "La grande conferenza tech a Modena"
    [languages.it.menus]
      [[languages.it.menus.main]]
      identifier = "agenda"
      name = "Agenda"
      url = "/2026/agenda/"
      weight = 1

      [[languages.it.menus.main]]
      identifier = "sessions"
      name = "Sessioni"
      url = "/2026/sessions/"
      weight = 2

      [[languages.it.menus.main]]
      identifier = "speakers"
      name = "Speaker"
      url = "/2026/speakers/"
      weight = 3

      [[languages.it.menus.main]]
      identifier = "location"
      name = "Location"
      url = "/location/"
      weight = 4

      [[languages.it.menus.main]]
      identifier = "communities"
      name = "Community"
      url = "/2026/communities/"
      weight = 5

      [[languages.it.menus.main]]
      identifier = "team"
      name = "Team"
      url = "/2026/team/"
      weight = 6

      [[languages.it.menus.main]]
      identifier = "faq"
      name = "FAQ"
      url = "/faq/"
      weight = 7

      [[languages.it.menus.footer]]
      identifier = "wtm"
      name = "Women Techmakers Modena"
      url = "https://wtm.modena.it"
      weight = 1
      [languages.it.menus.footer.params]
      external = true

  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    languageDirection = "ltr"
    title = "DevFest Modena 2026"
    weight = 2
    [languages.en.params]
      brand = "DevFest Modena"
      tagline = "The community tech conference in Modena"
    [languages.en.menus]
      [[languages.en.menus.main]]
      identifier = "agenda"
      name = "Agenda"
      url = "/2026/agenda/"
      weight = 1

      [[languages.en.menus.main]]
      identifier = "sessions"
      name = "Sessions"
      url = "/2026/sessions/"
      weight = 2

      [[languages.en.menus.main]]
      identifier = "speakers"
      name = "Speakers"
      url = "/2026/speakers/"
      weight = 3

      [[languages.en.menus.main]]
      identifier = "location"
      name = "Location"
      url = "/location/"
      weight = 4

      [[languages.en.menus.main]]
      identifier = "communities"
      name = "Communities"
      url = "/2026/communities/"
      weight = 5

      [[languages.en.menus.main]]
      identifier = "team"
      name = "Team"
      url = "/2026/team/"
      weight = 6

      [[languages.en.menus.main]]
      identifier = "faq"
      name = "FAQ"
      url = "/faq/"
      weight = 7

      [[languages.en.menus.footer]]
      identifier = "wtm"
      name = "Women Techmakers Modena"
      url = "https://wtm.modena.it"
      weight = 1
      [languages.en.menus.footer.params]
      external = true
