baseURL = "https://devfest.modena.it/"
title = "DevFest Modena 2025"

# Language
defaultContentLanguage = "it"
languageCode = "it-IT"

# Output
disableKinds = ["taxonomy"]
disableHugoGeneratorInject = true
enableGitInfo = true
enableRobotsTXT = true

# Markup
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
[markup.goldmark]
[markup.goldmark.renderHooks]
[markup.goldmark.renderHooks.link]
enableDefault = true

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate", ":fileModTime"]

# Custom params

[params]
author = "GDG Cloud Modena"
company = "GDG Cloud Modena"
email = "info@devfest.modena.it"
subject = "evento, event, tech, stem, devfest"
copyrightFromYear = 2024
favicon = true
hidden = false
simpleAnalyticsDomain = "sa.devfest.modena.it"
utm = "utm_source=website&utm_medium=referral&utm_campaign=devfest_modena_2025"
ticketsUrl = "https://devfest-modena-2025.eventbrite.it"
currentEdition = 2025

[params.social]
LinkedIn = "https://www.linkedin.com/showcase/devfest-modena/"
Instagram = "https://www.instagram.com/devfest.modena/"
Facebook = "https://www.facebook.com/events/1308374207349867"
Telegram = "https://t.me/devfest_modena"

# Memu

[menus]

# Main menu

[[menus.main]]
identifier = "agenda"
name = "Agenda"
url = "/2025/sessions/"
weight = 1

[[menus.main]]
identifier = "team"
name = "Team"
weight = 3
url = "/2025/team/"

[[menus.main]]
identifier = "tickets"
name = "Biglietti"
url = "https://devfest-modena-2025.eventbrite.it"
weight = 2
[menus.main.params]
external = true

# Footer menu

[[menus.footer]]
identifier = "wtm"
name = "Women Techmakers Modena"
url = "https://wtm.modena.it"
weight = 1
[menus.footer.params]
external = true
