**Analysis by Phase** During the phase-wise analysis, we focused on Phase 1 (P1) and examined the edges of the IFT that are mitigated by CE, AC and CE+AC. The analysis of this method is depicted in the Table 1 column named _CE at P1_, _AC at P1_ and _CE+AC at P1_. When we examined the attack paths mitigated by use of CE in P1, our analysis revealed that there were 6 cases where 2 edges were inhibited, 21 cases where 1 edge was inhibited, and 18 cases where no edges were inhibited. Regarding the use of AC in P1, there were 42 cases where no AC was required and 3 cases where 1 edge was inhibited by AC. The combination of controls in P1 showed that there were 19 cases where no edges were inhibited, 25 cases where 1 edge was inhibited, and 1 case where both controls stopped 2 edges.

The analysis highlights that CE played a crucial role in stopping attacks during the initial stage in most cases. However, layering with AC in some instances could further enhance the security posture by inhibiting attack pathways.

**Analysis by L1P1** The combination of level-wise and phase-wise analysis revealed that CE plays a major role in stopping the malicious edges. The findings are presented in the last three columns in Table 1. There are no more than two edges appearing in the L1P1 of IFT. The majority of 1's are occupied by CE alone, and there are only three cases - 02, 03 and 07 - where AC alone are used. This shows that CE alone is very effective in stopping the threats at an early stage. However, the number of edges in CE+AC should also be taken into account, and a total of 19 cases are observed to be mitigated by combined controls. This analysis shows that even though CE plays a major role as a standalone control, a combined approach provides further defence.

The summarised findings are presented in Table 2, encapsulating the key insights from the analysis. It is evident that in the Edge and Level analysis, the majority of attack pathways are effectively inhibited by the implementation of CE controls alone. However, it should be noted that AC measures also play a vital role in completely halting the attacks. In the Phase analysis, 17 out of 45 cases were successfully stopped solely by CE controls, while 28 cases required a layered approach incorporating both CE and AC controls. Particularly noteworthy is the effectiveness of CE controls in the L1P1 analysis, where 25 out of the 45 attacks were exclusively prevented by CE measures. This analysis underscores the significance of deploying CE controls at the lower levels of attacks during their initial phases, as it can effectively impede the spread of attacks further.

### RQ2: Which AC appear frequently and how effective are they as inhibitors of attack pathways.

After conducting a thorough analysis of the data, we have identified five AC, on top of CE, that are frequently used to prevent attacks from succeeding. These controls include Encryption, Backup, Policy, Education, and Logging & Monitoring.

* ***Education:** This control refers to education and training for users on cyber security best practices. By providing employees with regular cyber security training, organisations can reduce the risk of human error and strengthen their overall security posture. From the analysis of the 45 cyber incidents, several pathways were successfully inhibited by implementing AC. As illustrated in Figure 9, education was effective in 23 out of 45 incidents. This suggests that educating employees about cyber security best practices and potential threats is crucial in reducing the likelihood of successful cyber attacks, such as phishing.
* ***Logging & Monitoring:** Logging & Monitoring involves collecting and analysing network activities and security events. These activities include monitoring network traffic, log files and end-user activities. This control is important for identifying security incidents and minimising the damage caused. Logging & Monitoring was found to be effective in 26 out of 45 incidents in inhibiting attack edges. This indicates that closely monitoring system logs and network activities can effectively detect and prevent cyber attacks.