Somewhat of a contrast emerges when we combine L1 and P1. Figure 10 (d) shows that CE controls by themselves can be applied to prevent all the attack pathways in 6 of the 9 incidents of ransomware attack. Case 6 is a departure, where AC are applicable to prevent all the attack pathways and for cases 2 & 9, we need to apply AC and a combination of CE & AC respectively.

While looking at specific controls (Table 3), we find that CE controls such as Firewall and Secure Configuration were overwhelmingly applicable. For all the ransomware incidents Secure Configuration was the most commonly applicable CE control, followed by Malware Protection. So far as the AC, we find Encryption and Backup were widely applicable.