newton and the next _inhibit gates_ in this sub-tree, such as malware protection and security update management, protect against malware and PowerShell vulnerabilities, respectively. There is an additional control of user education which can potentially prevent users from clicking links in suspicious emails. The incident report does not conclusively note the cause of the _network intrusion_ and points to either relevant CVEs related to PowerShell or malware downloaded through a phishing email. We represent this using an _OR gate_. Finally, _network intrusion_ could have been prevented through user access control and/or secure configuration.

Similarly, for _network infection_, creation of accounts, disabling windows defender and scheduling a task form the basic enablers and are the _basic events_. The _inhibit gate_ points to access control which could have prevented the malware from creating user accounts bypassing the privilege management infrastructure. A firewall is identified as a control at the _inhibit gate_ which could have prevented inbound connection to a remote desktop along with remote desktop hardening. PsExec and Qakbot exploited SMB shares to enable lateral movement. Privilege escalation, persistence, access to a remote desktop and lateral movement led to _network infection_. This attack sub-tree could have been prevented through secure configuration.

Finally, _data encryption & server shutdown_ were enabled by encrypting the virtual machines hosted on Hyper-V servers and files on domain controllers. They are classified as _basic events_ along with the attacker's ability to push out ransomware on end user devices in the estate. The intermediate events, such as gathering IP addresses, targeting internal IP addresses and preventing backups led to _data encryption & server shutdown_. These actions could have been prevented with an appropriately configured firewall since the attacker executed the attack remotely.

### Identifying Security Controls

In the IFTs, we employed three different kinds of controls: CE Controls, controls provided in the incident reports and controls we identified as relevant. After the completion of the model, we initiated an analysis of the potential intermediate events or basic events that CE can prevent. The security measures described in the incident report were also used for this purpose. Several of the suggested controls from the reports were already present in CE. We then proceeded to look for events that needed AC (either recommended in the reports or ones we identified from the literature). Once we identified controls for all the inhibit gates, two researchers discussed the best way to finalise the controls and concluded the process. As illustrated in Figure 3, inhibit gates with text inside are Cyber Essential controls and inhibit gates with shield symbol inside are AC.