## 6 Analysis

Analysis by EdgesTo determine the effectiveness of CE, we counted the number of edges that could have been prevented by CE in each IFT. Our definition of _edge_ involves linking two nodes by an inhibit gate. So we consider each instance of the inhibit gate in the IFT model as a single edge as shown in Figure 4 (a). If there are several inhibit gates connecting the source and destination node, we also treat them as a single edge (Figure 4 (b)). In every case, the source node is an AND/OR gate, and the destination node is an intermediate event.

Analysis by LevelFor this type of analysis, we first examine the inhibit gates at the lowest _level_ within each tree. As illustrated in Figure 5, a three-level tree structure is depicted, with levels denoted as L1, L2 and L3. The first two layers, L1 and L2, have two edges and three inhibit gates each. The top layer, L3, has only one edge and one inhibit gate. We focus on L1 of each tree and identify which paths are restricted by CE. By examining the lowest level, we can determine the effectiveness of the CE controls in preventing an attack from going further in the tree. If the CE controls prove inadequate, we then proceed to examine AC controls, as well as potential combinations of both.

Analysis by PhaseIn the phase-wise analysis, we divide the IFT model into distinct phases representing intermediate events occurring after the top-level event. Figure 6 illustrates a three-phase structure consisting of Phase 1 (P1), Phase 2 (P2), and Phase 3 (P3). P1 is the initial phase, the first intermediate event following the top level event. We analyse attack mitigation by CE in its initial phase P1. This allows us to determine the level of protection provided by CE in preventing attacks during the initial phase. Additionally, we examine the use of other controls, such as AC and combinations of CE and AC that are employed in P1.

Analysis by Level+PhaseIn this analysis, we integrated both level-wise and phase-wise analysis as illustrated in Figure 7. To begin with, we focused on examining the attack paths at the lowest level (L1) during the initial phase (P1), which we referred to as L1P1. Subsequently we analysed the security controls implemented at the corresponding L1P1. By combining these two insights, we delved deeper into assessing the effectiveness of both CE and AC controls. This comprehensive analysis allowed us to gain a more thorough understanding of the overall effectiveness of these controls to stop an attack during the initial stages.