## 7 Findings

### RQ1: Effectiveness of CE in inhibiting attack pathways.

The data presented in Figure 8 indicates the attacks inhibited by CE controls. Firewall and Secure Configuration were applicable in 39 out of 45 incidents, making them the most effective security measures in blocking malicious traffic and preventing unauthorised access. This is a promising indication that the attack pathways can be inhibited by proper configuration to minimise the risk of cyber attacks. User Access Control was suitable in 22 out of 45 incidents. Malware Protection was applicable in 25 out of the 45 incidents. Lastly, Security Update Management, which involves regularly updating systems and software to address security vulnerabilities, was only applicable in 19 out of the 45 incidents.

We present our findings in Table 1. As noted above, we took a holistic approach to answering this research question by evaluating each component of the attack tree under four distinct analytical outcomes: analysis-by-edge, analysis-by-level, analysis-by-phase and analysis-by-level+phase.