Analysis by EdgeThe mitigation of attack pathways in the analysis-by-edge approach are represented in the three columns of the Table 1 starting from third column, i.e., CE Edges. The Case 01 in Table 1 has 11 edges, of which 6 edges are inhibited by CE controls, 3 through AC and 2 edges are inhibited by a combination of both CE and AC. Case 04 too has 11 edges, where 8 edges are mitigated through CE controls, 1 edge through AC and 2 edges through a combination of both CE and AC. These two incidents have the maximum coverage of CE controls, yet AC are required for comprehensive mitigation of the threats.

There are 18 cases where only 2 edges are inhibited by CE controls alone. However, the total number of edges for these 18 cases ranges from 3 to 6. This means there remains the need for at least one AC along with the relevant CE control to mitigate each of the 18 incidents.

Case 07 has 10 edges, where 4 edges can be prevented through AC - which is the highest among all the cases requiring AC. There are 17 cases where a combination of CE and AC controls mitigate threats, but these cases do not have independent AC edges. So AC on their own cannot be effective without the relevant CE controls. Only two cases, namely 25 and 38, have the highest combinations of CE and AC edges, amounting to 3. Again, this shows that neither CE nor AC are effective on their own. There are 20 cases which have only 1 combined edge each. This indicates that a significant proportion of our cases require some combination of CE and AC (in this case, at least 1) to prevent attacks.

Analysis by LevelThe analysis-by-level also highlights the need for a combination of CE and AC. CE controls can only mitigate 4 edges from 2 of the 45 incidents at level 1. AC can prevent at most 2 edges at level 1, and they appear in 6 cases. A combination of both AC and CE prevent 2 edges at level 1 from 2 of 45 cases.